"""empty message

Revision ID: 167dcb792676
Revises: 
Create Date: 2020-09-20 12:24:41.536379

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '167dcb792676'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(80), nullable=True),
    sa.Column('last_name', sa.String(80), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_msg', sa.Text(), nullable=True),
    sa.Column('bot_response', sa.Text(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    op.drop_table('users')
    # ### end Alembic commands ###
